version: '3.1'

services:
  app-serve:
    build: .
    image: myapp
    command: mvn clean test
    expose:
      - 4200

  app-e2e-tests:
    image: myapp
    command: dockerize -wait tcp://app-serve:4200
      -wait tcp://selenium-chrome-standalone:4444
      -timeout 10s -wait-retry-interval 1s bash -c "npm run e2e"
    depends_on:
      - app-serve
      - selenium-chrome-standalone

  selenium-chrome-standalone:
    image: selenium/node-chrome
    expose:
      - 44444